# Generated by Django 3.1.4 on 2022-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surn_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('active_email_address', models.EmailField(max_length=254)),
                ('program_of_study', models.CharField(max_length=100)),
                ('active_phone_number', models.CharField(max_length=10)),
                ('membership_status', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate/NSP', 'Graduate/NSP'), ('Postgraduate/Schooling', 'Postgraduate/Schooling'), ('Alumni', 'Alumni')], max_length=50)),
                ('place_of_residence', models.CharField(max_length=100)),
                ('name_of_current_hostel', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
