# Generated by Django 3.1.4 on 2022-04-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surn_name',
        ),
    ]
