# Generated by Django 3.1.4 on 2022-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220402_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='active_email_address',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='active_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='program_of_study',
            new_name='programe_of_study',
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(help_text='this helps us to wish you a happy birthday when its your birthday'),
        ),
    ]
