# Generated by Django 3.1.4 on 2022-04-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_member_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('Welfare', 'Welfare'), ('Academic', 'Academic'), ('Isses with Hall/Hostel', 'Isses with Hall/Hostel'), ('Report Abuse', 'Report Abuse'), ('Other', 'Other')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
