# Generated by Django 3.1.4 on 2022-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_helpdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='email_or_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
