# Generated by Django 4.0.6 on 2022-07-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_post_content_alter_post_multiple_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_posted',)},
        ),
    ]
