# Generated by Django 4.0.6 on 2022-07-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_event_time_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='services.event'),
        ),
    ]
