# Generated by Django 3.2.5 on 2021-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspirant',
            options={'ordering': ('date_created',)},
        ),
    ]
